//n dimensional array
//1. limit (generated by user's donation decision)
//2. random number (generate on creation and fix)
//3. boolean indicating whether random number is <= limit. 
//4. Available for use: true/false
//5. time stamp pulled from "players", for sorting
//
Donations = new Mongo.Collection('donations');


//DonationsOneSchema = new SimpleSchema({
//    playerID: {type: String},
//    limit: {type: Number},
//    randomNumber: {type: Number},
//    DonationIndicator: {type: Number},
//    availableDonationIndicator: {type: Number},
//    timeStamp:{type: Number}
//});
//DonationsOne.attachSchema(DonationsOneSchema);
//




